---
docker_unit_after: "multi-user.target"
docker_storage_driver: overlay2
bootloader_update_command: grub2-mkconfig -o /etc/grub2.cfg
conntrack_module: nf_conntrack

docker_version_map:
  "20.10":
    name: 'Docker-CE'
    package:
      - docker-ce-20.10.*
      - docker-ce-cli-20.10.*
      - containerd.io-1.5.*
    repo: "https://download.docker.com/linux/centos/8/{{ 'aarch64' if ansible_architecture == 'aarch64' else 'x86_64' }}/stable"
    keys:
      server: https://download.docker.com/linux/centos/gpg
      id: 060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35
  "24.0":
    name: 'Docker-CE'
    package:
      - docker-ce-24.0.*
      - docker-ce-cli-24.0.*
      - containerd.io-1.6.*
    repo: "https://download.docker.com/linux/centos/8/{{ 'aarch64' if ansible_architecture == 'aarch64' else 'x86_64' }}/stable"
    keys:
      server: https://download.docker.com/linux/centos/gpg
      id: 060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35  

podman_version_map:
  "4":
    name: 'podman'
    package:
      - podman-4.*
      - podman-remote-4.*