---
docker_unit_after: "multi-user.target"
docker_storage_driver: overlay2
bootloader_update_command: update-grub
conntrack_module: xt_conntrack

# Docker version mapping
docker_version_map:
  "26.0":
    package:
      - docker-ce=5:26.0.*
      - docker-ce-cli=5:26.0.*
      - containerd.io
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    keys:
      server: https://download.docker.com/linux/ubuntu/gpg
      id: 0EBFCD88
  "27.0":
    package:
      - docker-ce=5:27.0.*
      - docker-ce-cli=5:27.0.*
      - containerd.io
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    keys:
      server: https://download.docker.com/linux/ubuntu/gpg
      id: 0EBFCD88