---
- name: Check if GRUB_CMDLINE_LINUX requires modification
  command: grep -q 'cgroup_enable=memory swapaccount=1 cgroup.memory=nokmem' /etc/default/grub
  register: grub_check
  failed_when: false
  changed_when: false

- name: Modify GRUB_CMDLINE_LINUX if needed
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=")(.*)(")$'
    line: '\1\2 cgroup_enable=memory swapaccount=1 cgroup.memory=nokmem\3'
  register: modify_grub_cmdline  
  when: grub_check.rc != 0

- name: Run bootloader update
  command: "{{ bootloader_update_command }}"
  register: bootloader_update_result
  failed_when:
    - bootloader_update_result is failed
    - bootloader_update_result.rc is defined and bootloader_update_result.rc != 0
  when: modify_grub_cmdline.changed
