---
- name: Ensure all hosts are reachable via SSH and then gather facts
  hosts: primary
  gather_facts: no

  pre_tasks:
    - name: Wait for SSH to become available
      wait_for_connection:
        timeout: 300

    - name: Gather facts now that all hosts are reachable
      setup:

  roles:
    - eceinstall
  vars:
    ece_primary: true

- hosts: secondary:tertiary
  gather_facts: true
  roles:
    - eceinstall
  vars:
    ece_roles: [director, coordinator, proxy, allocator]
