---
- hosts: primary
  gather_facts: true
  roles:
    - eceinstall
  vars:
    ece_primary: true

- hosts: secondary:tertiary
  gather_facts: true
  vars:
    ece_roles: [director, coordinator, proxy, allocator]
  tasks:
    - include_role:
        name: eceinstall
      when: installtype == "small"
