---
# ECE installation playbook for primary and secondary/tertiary nodes

- name: ECE install - primary node
  hosts: primary
  gather_facts: true
  roles:
    - eceinstall
  vars:
    ece_primary: true

- name: ECE install - secondary and tertiary nodes
  hosts: secondary:tertiary
  gather_facts: true
  roles:
    - eceinstall
  vars:
    ece_roles: [director, coordinator, proxy, allocator]
