---
- name: Remove podman
  package:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - podman
    - podman-remote
  register: remove_packages
  retries: 10
  delay: 30
  until: remove_packages is success

- name: disable SELinux
  selinux:
    state: disabled

- name: Install podman
  package:
    name: "{{ podman_version_map[podman_version]['package'] }}"
    state: present

- name: Verify that fs.may_detach_mounts is enabled
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^fs.may_detach_mounts'
    line: 'fs.may_detach_mounts = 1'
    create: yes
