---
- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true

- include_tasks: install_dependencies.yml
- include_tasks: install_docker.yml
  when: crt == "docker"
- include_tasks: install_podman.yml
  when: crt == "podman"
##  tags: [install_docker, destructive]
