---
- name: Remove nscd package
  package:
    name: nscd
    state: absent
  register: remove_packages
  retries: 10
  delay: 5
  until: remove_packages is succeeded
  ignore_errors: yes
  failed_when:
    - remove_packages is failed
    - remove_packages.rc is defined and remove_packages.rc != 0

- name: Install cloud-init package
  package:
    name: cloud-init
    state: present
  register: install_cloud_init
  retries: 3
  delay: 10
  until: install_cloud_init is succeeded
  ignore_errors: yes
  failed_when:
    - install_cloud_init is failed
    - install_cloud_init.rc is defined and install_cloud_init.rc != 0

- name: Install base dependencies - Debian based
  apt:
    name: 
      - xfsprogs
      - acl
      - lvm2
      - gnupg
    state: present
    update_cache: yes
  register: install_dependencies
  retries: 3
  delay: 10
  until: install_dependencies is succeeded
  ignore_errors: yes
  failed_when:
    - install_dependencies is failed
    - install_dependencies.rc is defined and install_dependencies.rc != 0

# - name: Install gnupg - Debian based
#   apt:
#     name: 
#       - gnupg
#     state: present
#     update_cache: yes
#   register: install_gnupg
#   retries: 3
#   delay: 10
#   until: install_gnupg is succeeded
#   ignore_errors: yes
#   failed_when:
#     - install_gnupg is failed
#     - install_gnupg.rc is defined and install_gnupg.rc != 0