--- 
# - name: Remove Docker packages
#   package:
#     name: "{{ item }}"
#     state: absent
#   vars:
#     packages:
#     - docker
#     - docker-ce
#     - docker-ce-cli
#     - containerd
#     - docker-buildx-plugin
#   with_items: "{{ packages }}"
#   register: remove_packages
#   retries: 10
#   delay: 5
#   until: remove_packages is succeeded
#   ignore_errors: yes
#   failed_when: remove_packages is failed and (remove_packages.results | selectattr('rc', 'defined') | map(attribute='rc') | select('eq', 0) | list | length == 0)

- name: Add Docker repository
  yum_repository:
    name: "{{ docker_version_map[docker_version]['name'] }}"
    description: "Docker repository"
    file: docker-ce
    baseurl: "{{ docker_version_map[docker_version]['repo'] }}"
    enabled: yes
    gpgcheck: no
  register: repo_installed
  retries: 10
  delay: 5
  until: repo_installed is succeeded
  ignore_errors: yes
  failed_when: repo_installed is failed and repo_installed.rc != 0

- name: Install Docker
  package:
    name: "{{ docker_version_map[docker_version]['package'] }}"
    state: present
  register: docker_installed
  retries: 3
  delay: 10
  until: docker_installed is succeeded
  ignore_errors: yes
  failed_when: docker_installed is failed and docker_installed.rc != 0

- name: Lock Docker package versions with dnf_versionlock
  community.general.dnf_versionlock:
    name:
      - docker-ce-20.10.*
      - docker-ce-cli-20.10.*
      - containerd.io-1.5.*
    state: present
  register: lock_packages
  failed_when: lock_packages is failed