---
- name: Setup variables
  ansible.builtin.include_tasks: "subtasks/setup_vars.yml"

- name: Configure OS specific tasks
  ansible.builtin.include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}/configure_os.yml"

- name: Install based on crt variable
  ansible.builtin.include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}/install_{{ crt }}.yml"
  when: crt in ['docker', 'podman']
  
- name: Create elastic user
  ansible.builtin.include_tasks: "subtasks/create_elastic_user.yml"

- name: Configure sysctl
  ansible.builtin.include_tasks: "subtasks/configure_sysctl.yml"

- name: Configure limits
  ansible.builtin.include_tasks: "subtasks/configure_limits.yml"

- name: Update GRUB
  ansible.builtin.include_tasks: "subtasks/update_grub.yml"

- name: Configure filesystem
  ansible.builtin.include_tasks: "subtasks/configure_filesystem.yml"

- name: Configure kernel modules
  ansible.builtin.include_tasks: "subtasks/configure_kernel_modules.yml"

- name: Wait for CRT install to finish
  ansible.builtin.async_status:
    jid: "{{ crt_installed.ansible_job_id }}"
  register: async_result
  until: async_result.finished # Loop until the 'finished' flag is true
  retries: 60                  # How many times to check
  delay: 15                    # Wait 15 seconds between checks

- name: Configure based on crt variable
  ansible.builtin.include_tasks: "subtasks/configure_{{ crt }}.yml"
  when: crt in ['docker', 'podman']

- name: Reboot
  ansible.builtin.include_tasks: "subtasks/reboot.yml"
